# Generated by Django 4.2.7 on 2025-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
